# Generated by Django 5.2 on 2025-04-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
        ('planoSaude', '0002_planosaude_cidade_planosaude_cnpj_planosaude_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='idPlano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planoSaude.planosaude'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
