# Generated by Django 5.2 on 2025-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_paciente_idplano_alter_paciente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='idPlano',
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
