# Generated by Django 5.2 on 2025-04-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_remove_paciente_idplano_paciente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cep',
            new_name='cependereco',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='cpf',
            new_name='documento',
        ),
    ]
