# Generated by Django 5.2 on 2025-04-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_rename_cep_paciente_cependereco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='cependereco',
            new_name='CEP',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='documento',
            new_name='CPF',
        ),
    ]
