# Generated by Django 5.2 on 2025-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_rename_cependereco_paciente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='CEP',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='CPF',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
