# Generated by Django 5.2 on 2025-04-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_alter_paciente_cep_alter_paciente_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
