# Generated by Django 5.2 on 2025-04-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_rename_cep_paciente_cep_rename_cpf_paciente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='dataCadastro',
            field=models.DateField(auto_now_add=True, default='2025-04-15'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
