# Generated by Django 5.2 on 2025-04-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0009_paciente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
