# Generated by Django 5.2 on 2025-04-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaMedica', '0001_initial'),
        ('medico', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='idMedico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
