# Generated by Django 5.2 on 2025-04-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichaMedica', '0002_fichamedica_idmedico_fichamedica_idpaciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
