# Generated by Django 5.2 on 2025-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agenda_idmedico_agenda_idpaciente_alter_agenda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='idPaciente',
        ),
        migrations.AddField(
            model_name='agenda',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agenda',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
