# Generated by Django 5.2 on 2025-04-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_agenda_idpaciente_agenda_nome_agenda_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descrição',
            field=models.TextField(blank=True, null=True),
        ),
    ]
