# Generated by Django 5.2 on 2025-04-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_agenda_descrição'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='descrição',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
