# Generated by Django 5.2 on 2025-04-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_rename_descrição_agenda_descricao'),
        ('medico', '0005_alter_medico_crm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='telefone',
        ),
        migrations.AddField(
            model_name='agenda',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='medico.medico'),
        ),
    ]
