# Generated by Django 5.2 on 2025-04-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_remove_agenda_nome_remove_agenda_telefone_and_more'),
        ('paciente', '0011_alter_paciente_cep_alter_paciente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
    ]
