# Generated by Django 5.2 on 2025-04-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0005_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(max_length=10),
        ),
    ]
