# Generated by Django 5.2 on 2025-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_medico_crm_medico_email_medico_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
