# Generated by Django 5.2 on 2025-04-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_medico_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='dataCadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
