# Generated by Django 5.2 on 2025-04-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0004_alter_medico_datacadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
