# Generated by Django 5.2 on 2025-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoSaude', '0002_planosaude_cidade_planosaude_cnpj_planosaude_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='planosaude',
            name='dataCadastro',
            field=models.DateField(auto_now_add=True, default='2025-04-15'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planosaude',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
