# Generated by Django 5.2 on 2025-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoSaude', '0003_planosaude_cep_planosaude_datacadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='numero',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
