# Generated by Django 5.2 on 2025-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planoSaude', '0004_planosaude_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosaude',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
