# Generated by Django 5.2 on 2025-04-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasPagar', '0001_initial'),
        ('fornecedor', '0002_alter_fornecedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaspagar',
            name='idFornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor'),
        ),
        migrations.AlterField(
            model_name='contaspagar',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
