# Generated by Django 5.2 on 2025-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contasReceber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataEmissao', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('tipoConta', models.CharField(max_length=100)),
                ('dataVencimento', models.DateField()),
                ('dataPagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('formaPagamento', models.CharField(max_length=100)),
                ('centroReceita', models.CharField(max_length=100)),
                ('dataRecebimento', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
