# Generated by Django 5.2 on 2025-04-10 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contasReceber', '0001_initial'),
        ('medico', '0002_medico_crm_medico_email_medico_especialidade_and_more'),
        ('paciente', '0002_paciente_idplano_alter_paciente_id'),
        ('planoSaude', '0002_planosaude_cidade_planosaude_cnpj_planosaude_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasreceber',
            name='idMedico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medico.medico'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='idPlanos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planoSaude.planosaude'),
        ),
        migrations.AlterField(
            model_name='contasreceber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
