# Generated by Django 5.2 on 2025-04-23 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contasReceber', '0002_contasreceber_idmedico_contasreceber_idpaciente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contasreceber',
            old_name='idPlanos',
            new_name='idPlano',
        ),
        migrations.RemoveField(
            model_name='contasreceber',
            name='dataPagamento',
        ),
    ]
